#!/usr/bin/env bash
# Template for a project's .agents/prepare script (Delta runs it in every
# managed checkout it creates). Adapt it to your project; see Delta's
# "Prepare your project" docs for the exact contract.
#
# Problem it solves: concurrent agents each get their own checkout but share
# one machine, so test suites collide on ports, Erlang node names / epmd,
# and test database names. This script claims a unique numeric slot per
# checkout and writes .delta-env, which the orchestrate skill sources before
# every VERIFY command.
#
# Environment:
#   DELTA_SLOTS_DIR   where slot claims live (default ~/.cache/delta-slots)
#   DELTA_MAX_SLOTS   number of slots (default 99)
set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)"
slots_dir="${DELTA_SLOTS_DIR:-$HOME/.cache/delta-slots}"
max_slots="${DELTA_MAX_SLOTS:-99}"
mkdir -p -- "$slots_dir"

claim() { # $1=slot; atomic via mkdir
  local d="$slots_dir/$1"
  if mkdir -- "$d" 2>/dev/null; then
    printf '%s\n' "$root" > "$d/owner"
    return 0
  fi
  return 1
}

slot=""
# 1. Reuse this checkout's existing claim, so reruns keep the same slot.
for d in "$slots_dir"/*/; do
  [ -f "${d}owner" ] || continue
  if [ "$(cat -- "${d}owner")" = "$root" ]; then
    slot="$(basename -- "$d")"
    break
  fi
done

# 2. Otherwise claim the first free slot, reclaiming slots whose checkout is gone.
if [ -z "$slot" ]; then
  for n in $(seq 1 "$max_slots"); do
    if claim "$n"; then slot="$n"; break; fi
    owner="$(cat -- "$slots_dir/$n/owner" 2>/dev/null || true)"
    if [ -n "$owner" ] && [ ! -d "$owner" ]; then
      rm -rf -- "${slots_dir:?}/$n"
      if claim "$n"; then slot="$n"; break; fi
    fi
  done
fi
[ -n "$slot" ] || { echo "prepare: no free slot in $slots_dir (max $max_slots)" >&2; exit 1; }

env_file="$root/.delta-env"
tmp="$(mktemp "${env_file}.XXXXXX")"
{
  printf '# Generated by .agents/prepare for %s. Source before tests: . ./.delta-env\n' "$root"
  printf 'export DELTA_SLOT=%s\n' "$slot"
  # Elixir/Phoenix: Ecto test configs generated by Phoenix append this to the DB name.
  printf 'export MIX_TEST_PARTITION=%s\n' "$slot"
  # Ten ports per slot: PORT .. PORT+9.
  printf 'export PORT=%s\n' "$((4000 + slot * 10))"
  # A private epmd per slot keeps distributed Erlang/Mnesia test nodes apart.
  printf 'export ERL_EPMD_PORT=%s\n' "$((43690 + slot))"
  # Rust: share compiled artifacts across checkouts; keep target/ per checkout.
  if command -v sccache >/dev/null 2>&1; then
    printf 'export RUSTC_WRAPPER=sccache\n'
    printf 'export SCCACHE_DIR=%s\n' "${SCCACHE_DIR:-$HOME/.cache/sccache}"
  fi
} > "$tmp"
mv -f -- "$tmp" "$env_file"

# Keep .delta-env out of git status and out of Delta's synced files.
if git -C "$root" rev-parse --git-dir >/dev/null 2>&1; then
  exclude="$(git -C "$root" rev-parse --git-path info/exclude)"
  case "$exclude" in /*) ;; *) exclude="$root/$exclude" ;; esac
  mkdir -p -- "$(dirname -- "$exclude")"
  grep -qxF '.delta-env' "$exclude" 2>/dev/null || printf '%s\n' '.delta-env' >> "$exclude"
fi

# Per-checkout dependency setup. Keep what applies to the project.
[ -f "$root/mix.exs" ]    && (cd "$root" && mix deps.get)
[ -f "$root/Cargo.toml" ] && (cd "$root" && cargo fetch)

# Context indexes (tgrep, CodeGraph, zvec). Delta has no SessionStart hook, so
# feed the Codex index maintainer the same payload its hook would send. It is
# bounded, per-worktree locked, and fail-open; run it detached so creating the
# checkout is not delayed. Set DELTA_PREPARE_INDEXES=0 to skip (for example on
# short-lived subagent copies when many agents run at once).
ensure="$HOME/.codex/hooks/ensure-context-indexes.py"
if [ "${DELTA_PREPARE_INDEXES:-1}" != 0 ] && [ -f "$ensure" ] && command -v python3 >/dev/null 2>&1; then
  log="${DELTA_SCRATCH_DIR:-${TMPDIR:-/tmp}}/context-indexes.log"
  python3 -c 'import json,sys;print(json.dumps({"hook_event_name":"SessionStart","cwd":sys.argv[1]}))' "$root" \
    | nohup python3 "$ensure" >>"$log" 2>&1 &
fi

echo "prepare: $root -> slot $slot"
